#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! npx --no eslint src/ --max-warnings=0 --fix; then
  echo "I CATCH THE IMPOSTER!!"
  echo "Не выполнять коммиты из prod окружения!"
  exit 1
fi
